#help - wysyła komendy
#daily - codziennie bonus 250 darmowych monet
#ruletka - usuwa losowego członka grupy (bot musi mieć admina)
#luckymember - losuje losowego członka grupy
#depozyt - wpłaty do "bankowego sejfu"


#utrudnieniawroclaw - pisze utrudnienia w komunikacji miejskiej we Wrocławiu

#utrudnieniawawa - pisze utrudnienia w komunikacji miejsiej w Warszawie

#utrudnienialodz - pisze utrudnienia w komunikacji miejskiej w Łodzi

#banan - pokazuje wielkość Twojego banana ;D

#mute - wycisza głupie odzywki bota na np 'co' + wyłącza komendę !everyone


#unmute - odcisza bota

✨ Aby zobaczyć szczegółowe informacje na temat wybranej komendy, wpisz ‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎‎#pomoc <nazwa komendy>‎.
